version: '3.7'

services:
  php:
    container_name: projet_php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"

  mysql:
    image: mariadb:10.6.5-focal
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--max_allowed_packet=32505856"
    container_name: projet_db
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base
    ports:
      - 3351:3306
    volumes:
      - data_db:/var/lib/mysql

volumes:
  data_db: