<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ0oyNx8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ0oyNx8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ0oyNx8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ0oyNx8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ0oyNx8\App_KernelDevDebugContainer([
    'container.build_hash' => 'J0oyNx8',
    'container.build_id' => 'd81e20eb',
    'container.build_time' => 1717791304,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ0oyNx8');
