<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIx8NX40\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIx8NX40/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIx8NX40.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIx8NX40\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIx8NX40\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ix8NX40',
    'container.build_id' => '06bf6033',
    'container.build_time' => 1717774516,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIx8NX40');
